apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gors
spec:
  replicas: 5
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver-app
        image: lesteven/goserver
        envFrom:
        - configMapRef:
            name: my-config
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: golb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goserver
