
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    rel: beta
    app: backend
spec:
  containers:
  - image: lesteven/node2
    name: node2
    ports:
    - containerPort: 3000
      protocol: TCP
