apiVersion: v1
kind: ReplicationController
metadata:
  name: repcon
spec:
  replicas: 3
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: lesteven/node2
        ports:
        - containerPort: 3000
