apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: lesteven/node2
        ports:
        - containerPort: 3000
