apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: lesteven/node2
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: rslb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello
